# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=512)),
                ('imagen', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('idcategoria', models.ForeignKey(blank=True, db_column='idcategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
