# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=256)),
                ('condicion', models.BooleanField(default=1)),
            ],
        ),
    ]
